#ifndef BBK9288S_COMPAT_GUI_H
#define BBK9288S_COMPAT_GUI_H

/*
 * Slot numbers are generated from the 9288S SDK RT_GUI.h configuration with
 * _CTRL_BUTTON, _CTRL_STATIC, GUI_MEMORYSUPPORT, _GB_SUPPORT, and
 * _ToUnic_SUPPORT enabled.
 */
enum compat_gui_slot {
    COMPAT_GUI_GET_MESSAGE = 12,
    COMPAT_GUI_HAVE_PENDING_MESSAGE = 13,
    COMPAT_GUI_PEEK_POST_MESSAGE = 14,
    COMPAT_GUI_POST_MESSAGE = 15,
    COMPAT_GUI_SEND_MESSAGE = 16,
    COMPAT_GUI_SEND_NOTIFY_MESSAGE = 17,
    COMPAT_GUI_BROADCAST_MESSAGE = 18,
    COMPAT_GUI_POST_QUIT_MESSAGE = 19,
    COMPAT_GUI_TRANSLATE_MESSAGE = 20,
    COMPAT_GUI_DISPATCH_MESSAGE = 21,
    COMPAT_GUI_SET_INSTANT_PAINT = 29,
    COMPAT_GUI_CREATE_MAIN_WINDOW = 33,
    COMPAT_GUI_DESTROY_MAIN_WINDOW = 34,
    COMPAT_GUI_DEFAULT_MAIN_WIN_PROC = 35,
    COMPAT_GUI_UPDATE_WINDOW = 37,
    COMPAT_GUI_INVALIDATE_RECT = 56,
    COMPAT_GUI_BEGIN_PAINT = 57,
    COMPAT_GUI_END_PAINT = 58,
    COMPAT_GUI_CLIENT_TO_SCREEN = 61,
    COMPAT_GUI_SHOW_WINDOW = 77,
    COMPAT_GUI_MAIN_WINDOW_CLEANUP = 95,
    COMPAT_GUI_CREATE_CONTROL = 105,
    COMPAT_GUI_DESTROY_CONTROL = 106,
    COMPAT_GUI_SET_TIMER = 107,
    COMPAT_GUI_KILL_TIMER = 108,
    COMPAT_GUI_MESSAGE_BOX = 174,
    COMPAT_GUI_GET_SYS_PIXEL_INDEX = 191,
    COMPAT_GUI_GET_GD_CAPABILITY = 192,
    COMPAT_GUI_GET_DC = 193,
    COMPAT_GUI_GET_CLIENT_DC = 194,
    COMPAT_GUI_RELEASE_DC = 195,
    COMPAT_GUI_GET_BK_COLOR = 202,
    COMPAT_GUI_GET_BK_MODE = 203,
    COMPAT_GUI_GET_TEXT_COLOR = 204,
    COMPAT_GUI_SET_BK_COLOR = 205,
    COMPAT_GUI_SET_BK_MODE = 206,
    COMPAT_GUI_SET_TEXT_COLOR = 207,
    COMPAT_GUI_GET_PEN_COLOR = 210,
    COMPAT_GUI_GET_BRUSH_COLOR = 211,
    COMPAT_GUI_GET_PEN_TYPE = 212,
    COMPAT_GUI_GET_BRUSH_TYPE = 213,
    COMPAT_GUI_SET_PEN_COLOR = 214,
    COMPAT_GUI_SET_BRUSH_COLOR = 215,
    COMPAT_GUI_SET_PEN_TYPE = 216,
    COMPAT_GUI_SET_BRUSH_TYPE = 217,
    COMPAT_GUI_SET_PIXEL = 218,
    COMPAT_GUI_SET_PIXEL_RGB = 219,
    COMPAT_GUI_RGB_TO_PIXEL = 222,
    COMPAT_GUI_LINE_TO = 223,
    COMPAT_GUI_MOVE_TO = 224,
    COMPAT_GUI_RECTANGLE = 227,
    COMPAT_GUI_SAVE_SCREEN_BOX = 254,
    COMPAT_GUI_PUT_SAVED_BOX_ON_SCREEN = 256,
    COMPAT_GUI_FILL_BOX = 259,
    COMPAT_GUI_SET_RECT = 268,
    COMPAT_GUI_SET_RECT_EMPTY = 269,
    COMPAT_GUI_POINT_IN_RECT = 283,
    COMPAT_GUI_CREATE_LOG_FONT = 292,
    COMPAT_GUI_DESTROY_LOG_FONT = 294,
    COMPAT_GUI_TEXT_OUT_LEN = 316,
    COMPAT_GUI_DRAW_TEXT_EX = 318,
    COMPAT_GUI_PUT_IMAGE_AREA = 336,
    COMPAT_GUI_SET_HDC_FONT = 337,
    COMPAT_GUI_GET_HDC_FONT = 338,
    COMPAT_GUI_SET_SYS_FONT = 339,
    COMPAT_GUI_CLEAR_SCREEN = 340,
    COMPAT_GUI_GET_CURRENT_DATETIME = 351,
    COMPAT_GUI_SHOW_PICTURE_VIRTUAL = 355,
    COMPAT_GUI_SHOW_PICTURE_SCREEN = 356,
    COMPAT_GUI_REVERSE_SCREEN = 357,
    COMPAT_GUI_GET_PART_PICTURE_DATA = 358,
    COMPAT_GUI_BLIT_FRAME = 359,
    COMPAT_GUI_DRAW_ASCII = 360,
    COMPAT_GUI_DRAW_HZ = 361,
    COMPAT_GUI_PRINT_STRING = 362,
    COMPAT_GUI_CLEAR_RECT = 364,
    COMPAT_GUI_SHOW_STATUS_AND_DESKTOP = 388,
    COMPAT_GUI_REVERSE_RECT = 390,
    COMPAT_GUI_GET_BACKGROUND_PLAY_STATE = 392,
    COMPAT_GUI_MUSIC_VOLUME_SET = 403,
    COMPAT_GUI_MUSIC_VOLUME_GET = 404,
    COMPAT_GUI_SPEECH_OUTPUT_SET = 405,
    COMPAT_GUI_SPEECH_OUTPUT_GET = 406,
    COMPAT_GUI_MUSIC_OUTPUT_SET = 407,
    COMPAT_GUI_MUSIC_OUTPUT_GET = 408,
    COMPAT_GUI_SCAN_GAME_COMBO_KEYS = 419,
    COMPAT_GUI_RESET_AUTO_CLOSE_TIMER = 430,
    COMPAT_GUI_RESET_AUTO_CLOSE_LCD = 431,
    COMPAT_GUI_RESET_AUTO_CLOSE_LED = 432,
    COMPAT_GUI_GET_SCREEN_WIDTH = 437,
    COMPAT_GUI_GET_SCREEN_HEIGHT = 438,
    COMPAT_GUI_SET_LANDSCAPE = 439,
    COMPAT_GUI_GET_LANDSCAPE = 440,
    COMPAT_GUI_HELP2 = 448,
    COMPAT_GUI_TRACE_INIT = 449,
    COMPAT_GUI_ATTACH_ENABLE = 455,
    COMPAT_GUI_GET_BACKLIGHT_STATUS = 456,
    COMPAT_GUI_IS_SYSTEM_LOW_POWER = 457,
    COMPAT_GUI_LED = 459,
    COMPAT_GUI_DISPLAY_BACKLIGHT_STATUS = 460
};

enum compat_listbox_message {
    COMPAT_LB_ADDSTRING = 0xf180,
    COMPAT_LB_SETCURSEL = 0xf186,
    COMPAT_LB_GETCURSEL = 0xf188,
    COMPAT_LB_GETTEXT = 0xf189,
    COMPAT_LB_GETTEXTLEN = 0xf18a,
    COMPAT_LB_GETCOUNT = 0xf18b,
    COMPAT_LB_SETCARETINDEX = 0xf19e,
    COMPAT_LB_GETCARETINDEX = 0xf19f,
    COMPAT_LB_SETITEMHEIGHT = 0xf1a0
};

enum compat_gui_message {
    COMPAT_MSG_LBUTTONDOWN = 0x0001,
    COMPAT_MSG_LBUTTONUP = 0x0002,
    COMPAT_MSG_MOUSEMOVE = 0x0004,
    COMPAT_MSG_KEYDOWN = 0x0010,
    COMPAT_MSG_CREATE = 0x0060,
    COMPAT_MSG_DESTROY = 0x0064,
    COMPAT_MSG_CLOSE = 0x0066,
    COMPAT_MSG_PAINT = 0x00b1,
    COMPAT_MSG_TIMER = 0x0144
};

enum compat_gui_scancode {
    COMPAT_SCANCODE_ESCAPE = 1,
    COMPAT_SCANCODE_ENTER = 28,
    COMPAT_SCANCODE_UP = 103,
    COMPAT_SCANCODE_LEFT = 105,
    COMPAT_SCANCODE_RIGHT = 106,
    COMPAT_SCANCODE_DOWN = 108
};

#define COMPAT_MAIN_WIN_CREATE_PROC_OFFSET 24u
#define COMPAT_GUI_IMAGE_HEADER_SIZE 16u
#define COMPAT_GUI_TIMER_TICK_MS 10u

static inline unsigned compat_gui_timer_interval_ms(unsigned speed)
{
    return (speed ? speed : 1u) * COMPAT_GUI_TIMER_TICK_MS;
}

static inline unsigned compat_gui_packed_2bpp_stride(unsigned width)
{
    return (width + 3u) / 4u;
}

static inline unsigned compat_gui_packed_2bpp_payload_size(
    unsigned width,
    unsigned height
)
{
    return compat_gui_packed_2bpp_stride(width) * height;
}

static inline unsigned compat_gui_packed_2bpp_shift(unsigned x)
{
    return 6u - 2u * (x & 3u);
}

static inline unsigned compat_gui_image_payload_offset(
    const unsigned char *header,
    unsigned width,
    unsigned height,
    unsigned minimum_payload_size
)
{
    unsigned header_width =
        (unsigned)header[8] | ((unsigned)header[9] << 8);
    unsigned header_height =
        (unsigned)header[10] | ((unsigned)header[11] << 8);
    unsigned payload_size =
        (unsigned)header[12] |
        ((unsigned)header[13] << 8) |
        ((unsigned)header[14] << 16) |
        ((unsigned)header[15] << 24);

    return compat_gui_packed_2bpp_stride(header_width) ==
               compat_gui_packed_2bpp_stride(width) &&
           header_height == height &&
           payload_size >= minimum_payload_size
        ? COMPAT_GUI_IMAGE_HEADER_SIZE : 0u;
}

#endif
