#ifndef BBK9288S_COMPAT_GUI_H
#define BBK9288S_COMPAT_GUI_H

/*
 * Slot numbers are generated from the 9288S SDK RT_GUI.h configuration with
 * _CTRL_BUTTON, _CTRL_STATIC, and GUI_MEMORYSUPPORT enabled.
 */
enum compat_gui_slot {
    COMPAT_GUI_GET_MESSAGE = 12,
    COMPAT_GUI_SET_INSTANT_PAINT = 29,
    COMPAT_GUI_CREATE_MAIN_WINDOW = 33,
    COMPAT_GUI_DEFAULT_MAIN_WIN_PROC = 35,
    COMPAT_GUI_MAIN_WINDOW_CLEANUP = 95,
    COMPAT_GUI_SET_TIMER = 107,
    COMPAT_GUI_GET_SYS_PIXEL_INDEX = 191,
    COMPAT_GUI_GET_GD_CAPABILITY = 192,
    COMPAT_GUI_GET_DC = 193,
    COMPAT_GUI_GET_CLIENT_DC = 194,
    COMPAT_GUI_RELEASE_DC = 195,
    COMPAT_GUI_CLEAR_SCREEN = 336,
    COMPAT_GUI_GET_BACKGROUND_PLAY_STATE = 388
};

enum compat_gui_message {
    COMPAT_MSG_CREATE = 0x0060,
    COMPAT_MSG_PAINT = 0x00b1,
    COMPAT_MSG_TIMER = 0x0144
};

#define COMPAT_MAIN_WIN_CREATE_PROC_OFFSET 24u

#endif
